# -*- coding: utf-8 -*-
"""YOLOv5 Detection framework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULVE9TSeJT1iZWrRIK8Nf2rieDfliUxG

##Set up the Environment
"""

# Commented out IPython magic to ensure Python compatibility.
#Clone the Yolov5 repo
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt  # install dependencies
!pip install labelImg

"""##Mount Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""##Training YOLOv5 on a Video Dataset"""

video_path = '/content/drive/MyDrive/penguins_in_zoo.mp4'

# Run YOLOv5 inference on the sample image
!python detect.py --weights yolov5s.pt --source $video_path --conf 0.4 --save-txt --save-conf

!ls runs/detect/exp

from IPython.display import Video
Video('/content/drive/MyDrive/penguins_in_zoo.mp4', width=600, height=400, embed=True)

from google.colab import files
files.download('runs/detect/exp/penguins_in_zoo.mp4')